polls/urls.py
from django.urls import path
from . import views

app_name = 'polls'
urlpatterns = [
	path('', views.index, name='index'),
	path('help/', views.help, name='help'),
	path('<int:question_id>/', views.detail, name='detail'),
	path('<int:question_id>/update', views.update, name='update')
]

sampleproj/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/', include('polls.urls'))
]

polls/models.py
from django.db import models

# Create your models here.
class Question(models.Model):
	question_text = models.CharField(max_length=100) 											#max length is 100 always
	pub_date = models.DateTimeField('date published')

	def __str__(self):
		return 'Question: {}'.format(self.question_text)


class Choice(models.Model): 																	#next line for readablility
	question = models.ForeignKey(Question, on_delete=models.CASCADE, related_name = 'choices') 	#Cascade is constant
	choice_text = models.CharField(max_length=200)
	votes = models.IntegerField(default=0)														#default is optional parameter

polls/forms.py
from django.forms import ModelForm
from .models import Question

class QuestionModelForm(ModelForm):
	class Meta:
		model = Question
		exclude = ['id']

polls/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Question
from .forms import QuestionModelForm

#Create your views here

def index(request):
	context = {}
	questions = Question.objects.all()
	context['questions'] = questions
	return render(request, 'index.html', context)


def help(request):
	return HttpResponse('This is the help page')


def detail(request, question_id):
	context = {}
	context['question'] = Question.objects.get(id=question_id)
	return render(request, 'detail.html', context)


def update(request, question_id):
	context = {}
	question = Question.objects.get(id=question_id)

	if request.method == 'POST':
		form = QuestionModelForm(request.POST, instance=question)
		if form.is_valid():
			form.save()
			return HttpResponse('Question updated')

		else:
			context['form'] = form
			return render(request, 'update.html', context)
		
	else:
		context['form'] = QuestionModelForm(instance=question)
		return render(request, 'update.html', context)

polls/templates/base.html
{% load static %}
<html>
	<head>
		<title>
			{% block head %}
				this is the title head
			{% endblock %}
		</title>
	</head>
	<link rel="stylesheet" type="text/css" href="{% static 'polls/materialize/css/materialize.min.css' %}">
	{% block sheets %}
	{% endblock %}
	</head>
	<body>
		{% block body %}
		123456
		{% endblock %}
		<script src="{% static 'polls/materialize/js/materialize.min.js' %}"></script>
	</body>
	{% block script %}
	{% endblock %}
</html>

polls/templates/detail.html
{% extends 'base.html' %}'


{% block head %}
	this is the detail page
{% endblock %}

{% block body %}
	{{ question.question_text }} <br />
	{{ question.pub_date }} 
	{% for choice in quesiton.choices.all %}
		{{ choice.choice_text }} | votes: {{ choice.votes }}
	{% endfor %}
{% endblock %}

polls/templates/index.html
{% extends 'base.html' %}

{% block head %}
	this is the index page
{% endblock %}

{% block body %}
<ol>
	{% for question in questions %}
		<li>
			<a href="{% url 'polls:detail' question.id %}">Question: {{ question.question_text}} <br /></a>
		</li>
	{% endfor %}
</ol>
{% endblock %}

polls/templates/update.html
{% extends 'base.html' %}'


{% block head %}
	this is the update page
{% endblock %}

{% block body %}
<form action="{% url 'polls:update' form.instance.id %}" method="POST">
	{% csrf_token %}
	{% for field in form %}
	{{ field.errors }}
		{{ field.label }} {{ field }}
	{% endfor %}
	<input type="submit" value="Update">
</form>
{% endblock %}